### ISSUE TITLE
A memo about enabling x64 support in Windows Developer Console

### ISSUE THREAD

**Issue by noncom** [floooh/sokol-odin#7]
Just tried following the readme for building on Windows, from the Developer Prompt, but upon trying to run any of the `odin run ../examples/<example> -debug` instructions I was getting a lot of missing signature and linking errors like:

```powershell
PS C:\work\exp\odin\test-ws\sokol-odin\build>  odin run ../examples/clear -debug
clear.obj : error LNK2019: unresolved external symbol sapp_sgcontext referenced in function main.init
clear.obj : error LNK2019: unresolved external symbol sg_setup referenced in function main.init
clear.obj : error LNK2019: unresolved external symbol sg_query_backend referenced in function main.init
clear.obj : error LNK2019: unresolved external symbol sapp_width referenced in function main.frame
clear.obj : error LNK2019: unresolved external symbol sapp_height referenced in function main.frame
clear.obj : error LNK2019: unresolved external symbol sg_begin_default_pass referenced in function main.frame
clear.obj : error LNK2019: unresolved external symbol sg_end_pass referenced in function main.frame
clear.obj : error LNK2019: unresolved external symbol sg_commit referenced in function main.frame
clear.obj : error LNK2019: unresolved external symbol sg_shutdown referenced in function main.cleanup
clear.obj : error LNK2019: unresolved external symbol sapp_run referenced in function main.main
clear.obj : error LNK2001: unresolved external symbol slog_func
c:\work\exp\odin\test-ws\sokol-odin\sokol\log\sokol_log_windows_x64_d3d11_debug.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
c:\work\exp\odin\test-ws\sokol-odin\sokol\gfx\sokol_gfx_windows_x64_d3d11_debug.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
c:\work\exp\odin\test-ws\sokol-odin\sokol\app\sokol_app_windows_x64_d3d11_debug.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
c:\work\exp\odin\test-ws\sokol-odin\sokol\glue\sokol_glue_windows_x64_d3d11_debug.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
C:\work\exp\odin\test-ws\sokol-odin\build\clear.exe : fatal error LNK1120: 11 unresolved externals
PS C:\work\exp\odin\test-ws\sokol-odin\build> 
```

What I noticed though is that the `build_clibs_windows.cmd` command was using the `x86` compiler:

```powershell
PS C:\work\exp\odin\test-ws\sokol-odin> .\build_clibs_windows.cmd
Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32822 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

sokol_log.c
Microsoft (R) Library Manager Version 14.37.32822.0       
Copyright (C) Microsoft Corporation.  All rights reserved.

Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32822 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

sokol_app.c
Microsoft (R) Library Manager Version 14.37.32822.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32822 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

...etc...
```

And I'm on a x64 system, using a x64 build of Odin.

So I searched for that and found that this is a common problem and the Developer Prompt by default still lives in the 32bit era, and people are still confused by this and have been for years:
- https://developercommunity.visualstudio.com/t/x64-developer-powershell-for-vs-2019/943058
- https://developercommunity.visualstudio.com/t/powershell-does-not-correctly-set-up-developer-env/698236
- https://developercommunity.visualstudio.com/t/support-for-x64-and-other-target-platforms-other-t/927116

There is a way in the official Microsoft documentation of how to turn your default x86 Developer Console into a x64 one:
- https://developercommunity.visualstudio.com/t/support-for-x64-and-other-target-platforms-other-t/927116

Which is simply by adding the `-arch=amd64` parameter to your default Developer Console shortcut.
After this all goes fine:

```powershell
PS C:\work\exp\odin\test-ws\sokol-odin> .\build_clibs_windows.cmd
Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32822 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

...etc...
```
and the Odin examples build and start without a problem.

Since this is a problem that anyone working on a 64 bit platform should experience by default by Microsoft design, probably it would make sense to mention this way of dealing with it in the readme as well, and refer to the official example of fixing it? Or maybe just mention this issue since it's already a memo. Or something like that.

I can easily imagine how this would have taken another half an hour or so from me, if I haven't already stumbled on a similar problem with these tools recently. Anyone who's also not too familiar with Microsoft Development Console could get stuck here.

**Comment by floooh** [comment]
Hmm, I never experienced this issue. Do recent Visual Studio versions even still have the 32-bit developer prompt?

In general, the Odin bindings are tested on CI for Windows, first when generating the bindings here:

https://github.com/floooh/sokol/actions/runs/7086522618/job/19285198752

...and on each commit to the sokol-odin repo here:

https://github.com/floooh/sokol-odin/actions/runs/7086622423/job/19285242622

**Comment by pnarimani** [comment]
I had the same problem and solved it by using "x64 Native Tools Command Prompt" instead of the default Developer Command Prompt.

**Comment by noncom** [comment]
Sorry, the original reply went completely under my radar.
But yes, after gaining some more experience with these toolchains, I also tend to think what @pnarimani is saying.

Solution: Using the x64 version of the prompt actually sets up the environment for x64 support.
Closing this issue now.

> Do recent Visual Studio versions even still have the 32-bit developer prompt?

The default Native Tools Command Prompt without any bitness indication in the name indeed sets up the environment for 32bit. The absense of the indication of it in the name is what mislead me in the first place. [Here](https://learn.microsoft.com/en-us/answers/questions/635862/whats-the-differences-between-developer-command-pr) and [here](https://www.reddit.com/r/cpp/comments/bvrgmd/why_does_msvc_defaults_to_the_32_bit_toolset_on/) is some more info about it. Despite these references being a bit old, they still hold true, or at least held true at the date of my OP in this issue. The 2019 and 2022 MSVS installations indeed have/had a prompt setup that doesn't specify bitness but defaults to 32bit. No clue why this seemed to someone like a good idea.
